spring:
  datasource:
    url: jdbc:h2:mem:bankaccount
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081

