openapi: 3.0.0
info:
  title: RestAPI
  version: 1.0.0
  description: |
    Welcome to the RestAPI, a comprehensive interface catering to various banking and financial management needs. This API acts as a central hub, facilitating communication between different components for seamless execution of RESTful operations.


tags:
  - name: BankAccount

paths:
  /bankAccounts:
    get:
      summary: Get all Bank Accounts
      tags:
        - BankAccount
      responses:
        '200':
          description: Retrieve a list of all existing bank accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccount'

    post:
      summary: Create a new Bank Account
      tags:
        - BankAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'

      responses:
        '200':
          description: Bank Account created.

  /bankAccounts/{id}:
    get:
      summary: Get Bank Account by ID
      tags:
        - BankAccount
      parameters:
        - name: id
          in: path
          required: true
          description: Retrieve detailed information about a bank account using its unique identifier.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '404':
          description: Bank account not found

    patch:
      summary: Update Bank Account by ID
      tags:
        - BankAccount
      parameters:
        - name: id
          in: path
          required: true
          description: Retrieve detailed information about a bank account using its unique identifier.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
      responses:
        '200':
          description: Bank Account updated successfully
        '404':
          description: Bank account not found

    delete:
      summary: Delete a Bank Account
      tags:
        - BankAccount
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the bank account to delete
          schema:
            type: string
      responses:
        '200':
          description: Bank Account deleted successfully
        '404':
          description: Bank Account not found


components:
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          example: {"message": "Resource not found"}

    BadRequest:
      description: Bad request
      content:
        application/json:
          example: {"message": "Bad request"}
  schemas:
    BankAccount:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        balance:
          $ref: '#/components/schemas/MonetaryAmount'
        dispoLimit:
          $ref: '#/components/schemas/MonetaryAmount'
        labels:
          type: array
          items:
            type: string
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        referenceID:
          type: string
        labels:
          type: array
          items:
            type: string
        amount:
          $ref: '#/components/schemas/MonetaryAmount'
        description:
          type: string
        name:
          type: string
        type:
          type: string
          enum: [incoming, outgoing]


    MonetaryAmount:
      type: object
      properties:
        amount:
          type: number
          format: double
