openapi: 3.0.0
info:
  title: Transaction API
  version: 1.0.0
  description: Manage the lifecycle of one-time and recurring transactions.

tags:
  - name: One-Time Transaction

paths:
  /transactions/onetime:
    get:
      summary: Get all one-time transactions
      tags:
        - One-Time Transaction
      responses:
        '200':
          description: Successfully retrieved a list of all existing one-time transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OneTimeTransactionDto'

    post:
      summary: Create new one-time transaction
      tags:
        - One-Time Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OneTimeTransactionDto'

      responses:
        '200':
          description: Successfully created a new one-time transactions.

  /transactions/onetime/{id}:
    get:
      summary: Get one-time transaction by ID
      tags:
        - One-Time Transaction
      parameters:
        - name: id
          in: path
          required: true
          description: Transaction ID
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved one-time transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OneTimeTransactionDto'
        '404':
          description: One-Time transaction with given ID not found.

    patch:
      summary: Update one-time transaction by ID
      tags:
        - One-Time Transaction
      parameters:
        - name: id
          in: path
          required: true
          description: Transaction ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OneTimeTransactionDto'
      responses:
        '200':
          description: Successfully updated transaction.
        '404':
          description: One-Time transaction with given ID not found.

    delete:
      summary: Delete one-time Transaction by ID
      tags:
        - One-Time Transaction
      parameters:
        - name: id
          in: path
          required: true
          description: Transaction ID
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted one-time transaction.
        '404':
          description: One-Time transaction with given ID not found.

components:
  schemas:
    TransactionDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [INCOME, EXPENSE]
        labels:
          type: array
          items:
            type: string
        transfer:
          $ref: '#/components/schemas/TransferDto'

    OneTimeTransactionDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/TransactionDto'
        - $ref: '#/components/schemas/TransferableDto'

    TransferableDto:
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/MonetaryAmountDto'
        date:
          type: string
          format: Date

    TransferDto:
      type: object
      properties:
        sourceBankAccountId:
          type: string
          format: uuid
        externalSourceId:
          type: string
        targetBankAccountId:
          type: string
          format: uuid

    MonetaryAmountDto:
      type: object
      properties:
        amount:
          type: number
          format: double

    PeriodicityDto:
      type: string
      enum: [MONTHLY, QUARTERLY, HALF_YEARLY, YEARLY]
