plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

sidebar:
- label: Use Cases
  children:
    - ./pages/use_cases/use_case_descriptions_management_of_analytics.md
