remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
- label: Use Cases
  children:
    - uc-transaction

- label: Domain Models
  children:
    - domain-bankaccount
    - domain-transaction
    - domain-product
    - domain-savingsgoal
    - domain-analytics

- label: API Specifications
  children:
    - api-bankaccount
    - api-transaction
    - api-product
    - api-savingsgoal
    - api-analytics
