remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
- story

- label: Capabilities
  children:
    - capability-bankaccount
    - capability-transaction
    - capability-product
    - capability-savingsgoal
    - capability-analytics

- label: Use Cases
  children:
    - usecases-bankaccount
    - usecases-transaction
    - usecases-product
    - usecases-savingsgoal
    - usecases-analytics

- label: Domain Models
  children:
    - domain-bankaccount
    - domain-transaction
    - domain-product
    - domain-savingsgoal
    - domain-analytics

- label: API Specifications
  children:
    - api-bankaccount
    - api-transaction
    - api-product
    - api-savingsgoal
    - api-analytics

- scenario
