version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
    - "9093:9093"
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper

  bankaccount:
    container_name: bank-account
    build: ./implementation/bankaccount
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    ports:
      - 8081:8081
    links:
      - kafka
    depends_on:
      - kafka

  transaction:
    container_name: transaction
    build: ./implementation/transaction
    ports:
      - 8080:8080

