openapi: 3.0.0
info:
  title: Analytics
  version: 1.0.0
  description: Analyse finance data.


tags:
  - name: Analytics

paths:
  /budgetPlan:
    get:
      summary: Get a budget plan of all the data
      tags:
        - Analytics
      parameters:
        - name: monthlyAmount
          in: query
          required: true
          description: Retrieve the amount of money that has to be saved each month
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportFilterDto'
      responses:
        '200':
          description: Retrieve a budget plan of all the categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BudgetPlanDto'

  /forecast:
    get:
      summary: Create a new budget forecast for the bank accounts
      tags:
        - Analytics
      parameters:
        - name: date
          in: query
          required: true
          description: Retrieve a detailed forcast using its unique identifier.
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForecastDto'
        '404':
          description: Forecast not createable

  /nutrition:
    get:
      summary: Get the Nutrition in a given timeframe
      tags:
        - Analytics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DurationDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NutritionDto'
        '404':
          description: Nutrition values for this timeframe could not be found

  /report:
    get:
      summary: Get a report plan of all the data
      tags:
        - Analytics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportFilterDto'
      responses:
        '200':
          description: Retrieve a budget plan of all the categories
        '404':
          description: Report cound not be created

components:
  schemas:
    ReportFilterDto:
      type: object
      properties:
        categories:
          type: array
          items:
            type: string
        bankAccounts:
          type: array
          items:
            type: string
            format: uuid
        DurationDto:
          $ref: '#/components/schemas/DurationDto'

    DurationDto:
      type: object
      properties:
        startTime:
          type: string
        endTime:
          type: string

    BudgetPlanDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        achievementStatus:
          $ref: '#/components/schemas/BudgetAchievementStatusDto'
        plan:
          type: array
          items:
            $ref: '#/components/schemas/BudgetElementDto'
        date:
          type: string
          format: localDate

    BudgetAchievementStatusDto:
      type: string
      enum: [ ACHIEVED, FAILED ]

    BudgetElementDto:
      type: object
      properties:
        category:
          type: string
        monetaryAmount:
          $ref: '#/components/schemas/MonetaryAmountDto'

    ForecastDto:
      type: object
      properties:
        plan:
          type: array
          items:
            $ref: '#/components/schemas/ForecastElementDto'
        date:
          type: string
          format: localDate

    ForecastElementDto:
      type: object
      properties:
        bankAccount:
          type: string
          format: uuid
        monetaryAmount:
          $ref: '#/components/schemas/MonetaryAmountDto'

    MonetaryAmountDto:
      type: object
      properties:
        amount:
          type: number
          format: double

    NutritionDto:
      type: object
      properties:
        servingSize:
          type: number
          format: double
        calories:
          type: number
          format: double
        carbohydrates:
          type: number
          format: double
        protein:
          type: number
          format: double
        fat:
          type: number
          format: double
        sugar:
          type: number
          format: double
