spring:
  datasource:
    url: jdbc:h2:mem:transaction
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9093

server:
  port: 8080

bank-account: localhost

tpd:
  topic-oneTimeTransaction-update: oneTimeTransaction-update
  topic-recurringTransaction-update: recurringTransaction-update
  messages-per-request: 1