openapi: 3.0.0
info:
  title: Savings Goal
  version: 1.0.0
  description: Manage periodical and rule-based savings goals.


tags: 
  - name: Periodical Savings Goal
  - name: Rule Based Savings Goal

paths:
  /savings-goals/periodical:
    get:
      summary: Get all Periodical Savings Goals
      tags: 
        - Periodical Savings Goal
      responses:
        '200':
          description: Retrieve a list of all existing savings goals.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeriodicalSavingsGoalDto'
                  
    post:
      summary: Create a new Periodical Savings Goal
      tags: 
        - Periodical Savings Goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodicalSavingsGoalDto'
        
      responses:
        '200':
          description: Periodical Savings Goal created.

  /savings-goals/periodical/{id}:
    get:
      summary: Get Periodical Savings Goal by ID
      tags:
        - Periodical Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      responses:
        '200':
          description: Savings Goal retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeriodicalSavingsGoalDto'
        '404':
          description: Periodical Savings Goal not found.

    patch:
      summary: Update Periodical Savings Goal by ID
      tags:
        - Periodical Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeriodicalSavingsGoalDto'
      responses:
        '200':
          description: Periodical Savings Goal updated successfully
        '404':
          description: Periodical Savings Goal not found

    delete:
      summary: Delete Periodical Savings Goal by ID
      tags:
        - Periodical Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      responses:
        '200':
          description: Periodical Savings Goal deleted successfully
        '404':
          description: Periodical Savings Goal not found
                    
  /savings-goals/rule-based:
    get:
      summary: Get all Rule-based Savings Goals
      tags: 
        - Rule Based Savings Goal
      responses:
        '200':
          description: Retrieve a list of all existing rule-based savings goals.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RuleBasedSavingsGoalDto'
                    
    post:
      summary: Create a new Rule-based Savings Goal
      tags: 
        - Rule Based Savings Goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuleBasedSavingsGoalDto'
        
      responses:
        '200':
          description: Rule Based Savings Goal created.

  /savings-goals/rule-based/{id}:
    get:
      summary: Get Rule-based Savings Goal by ID
      tags:
        - Rule Based Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      responses:
        '200':
          description: Savings Goal retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuleBasedSavingsGoalDto'
        '404':
          description: Savings Goal not found
          
    patch:
      summary: Update Rule-based Savings Goal by ID
      tags:
        - Rule Based Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RuleBasedSavingsGoalDto'
      responses:
        '200':
          description: Rule Based Savings Goal updated successfully
        '404':
          description: Rule Based Savings Goal not found
          
    delete:
      summary: Delete Rule-based Savings Goal by ID
      tags:
        - Rule Based Savings Goal
      parameters:
        - name: id
          in: path
          required: true
          description: Savings Goal ID.
          schema:
            type: string
      responses:
        '200':
          description: Rule Based Savings Goal deleted successfully
        '404':
          description: Rule Based Savings Goal not found
  
components:
  schemas:
    SavingsGoalDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        achievementStatus:
          $ref: '#/components/schemas/AchievementStatusDto'

    AchievementStatusDto:
      type: string
      enum: [ IN_PROGRESS, ACHIEVED, FAILED ]
      
    PeriodicalSavingsGoalDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/SavingsGoalDto'
        - properties:
            sourceBankAccountID:
              type: string
              format: uuid
            targetBankAccountID:
              type: string
              format: uuid
            goal:
              $ref: '#/components/schemas/MonetaryAmountDto'
            recurringRate:
              type: number
              format: double
            recurringAmount:
              $ref: '#/components/schemas/MonetaryAmountDto'
            duration:
              type: string
            periodicity:
              $ref: '#/components/schemas/PeriodicityDto'

    RuleBasedSavingsGoalDto:
      type: object
      allOf:
        - $ref: '#/components/schemas/SavingsGoalDto'
        - properties:
            matchingType:
              $ref: '#/components/schemas/MatchingTypeDto'
            rules:
              type: array
              items:
                $ref: '#/components/schemas/RuleDto'
    RuleDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        bankAccountId:
          type: string
          format: uuid
        description:
          type: string
        type:
          $ref: '#/components/schemas/RuleTypeDto'
        target:
          $ref: '#/components/schemas/MonetaryAmountDto'
    
    MonetaryAmountDto:
      type: object
      properties:
        amount:
          type: number
          format: double
          
    PeriodicityDto:
        type: string
        enum: [MONTHLY, QUARTERLY, HALF_YEARLY, YEARLY]

    MatchingTypeDto:
      type: string
      enum: [ MATCH_ALL, MATCH_ANY ]

    RuleTypeDto:
      type: string
      enum: [ EQUALS, GREATER_THAN, LESS_THAN ]
