sequenceDiagram
    Transaction->>+BankAccount: addTransactionToAccount(accountId, transactionId)
    SavingsGoals->>+BankAccount: checkSavingsGoal(bankAccount)
    BankAccount-->>-SavingsGoals: done
    BankAccount-->>-Transaction: done
    Transaction->>+BankAccount: deleteTransaction(ccountId, transactionId)
    SavingsGoals->>+BankAccount: checkSavingsGoal(bankAccount)
    BankAccount-->>-SavingsGoals: done
    BankAccount-->>-Transaction: success
    Transaction->>+BankAccount: changeTransaction(ccountId, transactionId)
    SavingsGoals->>+BankAccount: checkSavingsGoal(bankAccount)
    BankAccount-->>-SavingsGoals: done
    BankAccount-->>-Transaction: success

    SavingsGoals->>+BankAccount: getBankAccount(Id)
    BankAccount-->>-SavingsGoals: done "no violation"
    