spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

tpd:
  topic1-name: transaction-queue
  topic2-name: transaction-backwards-queue
  messages-per-request: 1
