name: Spellcheck Action
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
      with:
        config_path: config/.spellcheck.yml
        source_files: README.md
        task_name: Markdown